networks:
  ocp-network:
    driver: bridge

x-common-settings: &common-settings
  networks:
    - ocp-network
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  cassandra:
    image: scylladb/scylla:latest
    command: --smp 1 --memory 750M
    ports:
      - "9942:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' 127.0.0.1 9042"]
      interval: 10s
      timeout: 5s
      retries: 30

  php:
    build:
      context: .
      target: runtime
    volumes:
      - .:/app
    environment:
      CASSANDRA_HOSTS: cassandra
      CASSANDRA_PORT: "9042"
    command: tail -f /dev/null
    <<: *common-settings
